services:
  - type: web
    name: cab-api
    runtime: node
    region: oregon
    plan: free
    buildCommand: cd api && npm install
    startCommand: cd api && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_SERVER
        sync: false
      - key: DB_PORT
        value: 1433
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: JWT_SECRET
        generateValue: true
